Repository ti-broish/admin, pull requests merged in 2023-03, with the labels that each got.

#71 Протоколи без секция в преброителния център
  src/components/modules/protocols/ProtocolDetails.js
  src/components/modules/protocols/ProtocolsHome.js
  src/components/process_protocols/VerifyProtocolInfo.js
  src/components/process_protocols/validation_form/SectionDetails.js
  src/components/process_protocols/validation_form/ValidationFormState.js
Labels: протоколи

#88 Show violation contact name when author is not a signed in user
  src/components/modules/violations/ViolationDetails.js
  src/components/modules/violations/ViolationList.js
Labels: сигнали

#87 Контролни проверки при валидиране на протокол - Part 2
  .editorconfig
  .gitignore
  README.md
  package.json
  src/common/enums/protocol-status.js
  src/common/enums/protocol-type.js
  src/components/modules/protocols/ProtocolDetails.js
  src/components/process_protocols/VerifyProtocolInfo.js
  src/components/process_protocols/protocol_photos/ProtocolPhotos.js
  src/components/process_protocols/request-example.txt
  src/components/process_protocols/validation_form/ProtocolForm.js
  src/components/process_protocols/validation_form/SectionDetails.js
  src/components/process_protocols/validation_form/ValidationFormState.js
  src/components/process_protocols/validation_form/validation-form-utils.js
  src/types/types-common.js
  src/types/types-protocol.js
  src/types/types-react.js
Labels: протоколи

#92 Support 3-digit country code in admin filters
  src/components/modules/admin/AdminFilter.js
  src/components/modules/filter_components/MainFilter.js
  src/components/modules/protocols/ProtocolFilter.js
  src/components/modules/violations/ViolationFilter.js
Labels: проблем, протоколи, сигнали

#93 Показване на номера на клетката при грешни контролни проверки в протокола
  src/components/process_protocols/validation_form/validation-form-utils.js
Labels: протоколи
